---
author: "Eduardo Yuki Yada"
geometry: margin=1cm
output: 
  pdf_document:
    template: latex-template.tex
params:
  outcome_column: death_30days
title: "`r paste('Plots -', params$outcome_column)`"
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  warning = F,
  message = F
)
```

# Imports

```{r warning=F, message=F}
library(tidyverse)
library(yaml)
```

# Loading data

```{r}
load('dataset/processed_data.RData') 
load('dataset/processed_dictionary.RData') 

columns_list <- yaml.load_file("./auxiliar/columns_list.yaml")

outcome_column <- params$outcome_column

df[columns_list$outcome_columns] <- lapply(df[columns_list$outcome_columns], as.character)
df[columns_list$outcome_columns] <- lapply(df[columns_list$outcome_columns], as.integer)
```

# Plots

```{r warning=F, fig.show="hold", out.width="50%", fig.height = 5}
df[columns_list$outcome_columns] <- lapply(df[columns_list$outcome_columns], factor)

for (column in columns_list$numerical_columns){
  if (mean(is.na(df[[column]])) > 0.95 | length(unique(df[[column]])) < 10) next
  
  df %>%
    ggplot(aes_string(x = outcome_column, y = column)) + 
      geom_boxplot(outlier.alpha = 0.1) + 
      theme_grey() -> p
      
  print(p)
}
```
